FROM node:22-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG VITE_API_URL=http://localhost:8000/api
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build
RUN npm install -g serve
EXPOSE 5173
CMD ["serve","-s","dist","-l","5173"]
