from datetime import datetime
from sqlalchemy import String,Text,Integer,DateTime,ForeignKey,JSON,Float,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from .db import Base
class User(Base):
    __tablename__="users"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120)); email:Mapped[str]=mapped_column(String(320),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(String(30),default="user"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); ideas:Mapped[list["Idea"]]=relationship(back_populates="user",cascade="all, delete-orphan")
class Idea(Base):
    __tablename__="ideas"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); title:Mapped[str]=mapped_column(String(200)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); user:Mapped[User]=relationship(back_populates="ideas"); versions:Mapped[list["IdeaVersion"]]=relationship(back_populates="idea",cascade="all, delete-orphan")
class IdeaVersion(Base):
    __tablename__="idea_versions"; __table_args__=(UniqueConstraint("idea_id","version_number"),); id:Mapped[int]=mapped_column(primary_key=True); idea_id:Mapped[int]=mapped_column(ForeignKey("ideas.id",ondelete="CASCADE"),index=True); version_number:Mapped[int]=mapped_column(Integer); problem:Mapped[str]=mapped_column(Text); solution:Mapped[str]=mapped_column(Text); target_users:Mapped[str]=mapped_column(Text); features:Mapped[list]=mapped_column(JSON); impact:Mapped[str]=mapped_column(Text); technology_preference:Mapped[str|None]=mapped_column(Text); team_size:Mapped[int]=mapped_column(Integer); team_skill_level:Mapped[str]=mapped_column(String(30)); hackathon_duration_hours:Mapped[int]=mapped_column(Integer); prototype:Mapped[str|None]=mapped_column(Text); constraints:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); idea:Mapped[Idea]=relationship(back_populates="versions"); evaluations:Mapped[list["Evaluation"]]=relationship(back_populates="version",cascade="all, delete-orphan")
class Evaluation(Base):
    __tablename__="evaluations"; id:Mapped[int]=mapped_column(primary_key=True); idea_version_id:Mapped[int]=mapped_column(ForeignKey("idea_versions.id",ondelete="CASCADE"),index=True); idea_quality_score:Mapped[float]=mapped_column(Float); build_feasibility_score:Mapped[float]=mapped_column(Float); hackathon_readiness_score:Mapped[float]=mapped_column(Float); analysis_json:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); version:Mapped[IdeaVersion]=relationship(back_populates="evaluations")
class Hackathon(Base):
    __tablename__="hackathons"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); name:Mapped[str]=mapped_column(String(200)); rules_text:Mapped[str]=mapped_column(Text); extracted_rules_json:Mapped[dict|None]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
